main: me.Plugins.Dowsing.DowsingMain
api-version: 1.20
name: Dowsing
version: 3.0.3
author: Drefvelin

depend: [MMOItems, MythicLib, ItemsAdder, LoneLibs, SimpleFactions]

commands:
  dowsing:
      useage: /<command>
      description: Dowsing Command